# Generated by Django 5.2 on 2026-02-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='instagram_comment_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_ALBUM', 'Carousel Album')], max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
